### ISSUE TITLE
Negative base support?

### ISSUE THREAD

**Issue by no-identd** [AdamRakaska/RadixCalculator#4]
🙃
```
************** Exception Text **************
System.ArgumentOutOfRangeException: Value must be a positive number.
Parameter name: DecimalValue
   at RadixCalculator.MixedRadixSystem.RadixNumeral.Increment(BigInteger DecimalValue)
   at RadixCalculator.MixedRadixSystem.RadixNumeral.Increment(BigInteger DecimalValue)
   at RadixCalculator.MixedRadixSystem.RadixNumeral.Increment()
   at RadixCalculator.MixedRadixSystem.Increment()
   at RadixCalculator.MainForm.BtnIncrementClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///[REDACTED_%windir%]/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
RadixCalculator
    Assembly Version: 1.0.6913.35720
    Win32 Version: 1.0.6913.35720
    CodeBase: file:///[REDACTED]/RadixCalculator.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///[REDACTED_%windir%]/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///[REDACTED_%windir%]/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///[REDACTED_%windir%]/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///[REDACTED_%windir%]/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2556.0 built by: NET471REL1
    CodeBase: file:///[REDACTED_%windir%]/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///[REDACTED_%windir%]/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2612.0 built by: NET471REL1LAST_B
    CodeBase: file:///[REDACTED_%windir%]/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

```
🙂

**Comment by AdamRakaska** [comment]
I should be able to make the application support negative base numbers. I was actually just thinking about this the other day, and I think its a feature I would like to add. Give me some time to think about how to best implement this and then implement it. For now, it will provide an error message.

**Comment by no-identd** [comment]
You might wish to compare to https://github.com/ThomasTheSpaceFox/BalTcalc & https://github.com/SBTCVM/libbaltcalc :)
